# Generated by Django 5.1.1 on 2024-09-29 10:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meds", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
