# Generated by Django 5.1.1 on 2024-09-29 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meds", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="dob",
            field=models.DateField(default=datetime.date(1999, 8, 16)),
        ),
        migrations.AddField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                choices=[
                    ("Male", "Male"),
                    ("Female", "Female"),
                    ("Not Specified", "Not Specified"),
                ],
                default="Not Specified",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="doctors",
            name="photo",
            field=models.ImageField(
                default="user-avatar.png", upload_to="static/photos"
            ),
        ),
    ]
