# Generated by Django 5.1.1 on 2024-10-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meds", "0005_alter_doctors_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctors",
            name="photo",
            field=models.ImageField(upload_to="profile_photos/"),
        ),
    ]
