# Generated by Django 5.1.1 on 2024-10-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meds", "0009_availability_max_appintments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availability",
            name="max_appintments",
            field=models.IntegerField(default=8),
        ),
    ]
