# Generated by Django 5.1.1 on 2024-10-24 03:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meds", "0011_appointment_delete_appointments"),
    ]

    operations = [
        migrations.RenameField(
            model_name="availability",
            old_name="max_appintments",
            new_name="max_appointments",
        ),
    ]
