# Generated by Django 5.1.1 on 2024-10-24 12:24

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meds", "0012_rename_max_appintments_availability_max_appointments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={"ordering": ["date", "start_time"]},
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="booked_count",
        ),
        migrations.AddField(
            model_name="appointment",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 24, 17, 54, 16, 588673)
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_appointments",
                to="meds.doctors",
            ),
        ),
    ]
