# Generated by Django 5.1.1 on 2025-02-01 09:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meds", "0014_alter_appointment_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="availability",
            name="break_from",
            field=models.TimeField(default=datetime.time(13, 0)),
        ),
        migrations.AddField(
            model_name="availability",
            name="break_to",
            field=models.TimeField(default=datetime.time(14, 0)),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 2, 1, 15, 6, 29, 317924)
            ),
        ),
        migrations.CreateModel(
            name="OnlineAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                            ("Sunday", "Sunday"),
                        ],
                        max_length=10,
                    ),
                ),
                ("available_from", models.TimeField()),
                ("available_to", models.TimeField()),
                ("max_appointments", models.IntegerField(default=8)),
                ("break_from", models.TimeField()),
                ("break_to", models.TimeField()),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_availabilities",
                        to="meds.doctors",
                    ),
                ),
            ],
        ),
    ]
