# Generated by Django 5.1.1 on 2025-02-06 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meds", "0015_availability_break_from_availability_break_to_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 2, 6, 15, 31, 20, 73037)
            ),
        ),
    ]
