# Generated by Django 5.1.1 on 2025-02-06 11:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meds", "0017_alter_appointment_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 2, 6, 17, 14, 25, 182104)
            ),
        ),
        migrations.AlterField(
            model_name="onlineavailability",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="online_availabilities_fulltime",
                to="meds.doctors",
            ),
        ),
        migrations.CreateModel(
            name="OnlineAvailabilityPartime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                            ("Sunday", "Sunday"),
                        ],
                        max_length=10,
                    ),
                ),
                ("available_from", models.TimeField()),
                ("available_to", models.TimeField()),
                ("max_appointments", models.IntegerField(default=8)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_availabilities_partime",
                        to="meds.doctors",
                    ),
                ),
            ],
        ),
    ]
