# Generated by Django 5.1.1 on 2025-02-08 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meds", "0018_alter_appointment_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="patient",
            new_name="booked_by",
        ),
        migrations.AddField(
            model_name="appointment",
            name="appointment_mode",
            field=models.CharField(
                choices=[("offline", "Offline"), ("online", "Online")],
                default="offline",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient_name",
            field=models.TextField(default="basit"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="appointment",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 2, 8, 15, 31, 17, 828838)
            ),
        ),
    ]
