# Generated by Django 5.1.1 on 2025-02-08 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meds", "0019_rename_patient_appointment_booked_by_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment",
            old_name="booked_by",
            new_name="patient",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="patient_name",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 2, 8, 15, 36, 54, 365363)
            ),
        ),
    ]
