# Generated by Django 5.1.1 on 2025-02-09 19:08

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meds", "0020_rename_booked_by_appointment_patient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="username",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="appointment",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 2, 10, 0, 38, 8, 441908)
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="patient",
            field=models.TextField(),
        ),
    ]
