# Generated by Django 5.1.1 on 2025-02-11 01:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meds", "0021_appointment_username_alter_appointment_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 2, 11, 6, 49, 29, 700501)
            ),
        ),
    ]
