# Generated by Django 5.1.1 on 2025-02-12 11:34

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meds", "0023_alter_appointment_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="channel_name",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 2, 12, 17, 4, 1, 398836)
            ),
        ),
    ]
