# Generated by Django 5.1.1 on 2025-02-12 11:37

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("meds", "Appointment")
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["channel_name"])

class Migration(migrations.Migration):
    dependencies = [
        ("meds", "0024_appointment_channel_name_and_more"),
    ]

    operations = [migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),]
