# Generated by Django 5.1.1 on 2025-02-12 11:38

from django.db import migrations , models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("meds", "0025_auto_20250212_1707"),
    ]

    operations = [ migrations.AlterField(
            model_name="appointment",
            name="channel_name",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),]
