# Generated by Django 5.1.1 on 2025-02-14 11:26

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meds", "0026_auto_20250212_1708"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="channel_name",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 2, 14, 16, 56, 32, 806468)
            ),
        ),
        migrations.CreateModel(
            name="DoctorRequests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("degree", models.CharField(max_length=50)),
                ("specialization", models.CharField(max_length=50)),
                ("address", models.TextField()),
                ("experience", models.TextField(default=0, max_length=5)),
                ("photo", models.ImageField(upload_to="profile_photos/")),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
