# Generated by Django 5.1.1 on 2025-02-14 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meds", "0028_alter_appointment_created_at_verificationdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 2, 14, 23, 46, 58, 813051)
            ),
        ),
    ]
