# Generated by Django 5.1.1 on 2025-02-14 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meds", "0029_alter_appointment_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="verificationdata",
            name="user",
        ),
        migrations.AddField(
            model_name="verificationdata",
            name="email",
            field=models.EmailField(default="a@gmail.com", max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="appointment",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 2, 15, 0, 21, 2, 73452)
            ),
        ),
    ]
