# Generated by Django 5.1.1 on 2025-02-14 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meds", "0030_remove_verificationdata_user_verificationdata_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 2, 15, 0, 23, 2, 422876)
            ),
        ),
    ]
