# Generated by Django 5.1.1 on 2025-02-14 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meds", "0032_alter_appointment_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 2, 15, 1, 49, 1, 355401)
            ),
        ),
    ]
