# Generated by Django 5.1.1 on 2025-03-03 09:43

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meds", "0034_alter_appointment_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 3, 3, 15, 13, 17, 39715)
            ),
        ),
        migrations.CreateModel(
            name="BMI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.TextField()),
                ("height", models.TextField()),
                ("bmi", models.TextField()),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="username",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
