# Generated by Django 5.1.1 on 2025-03-03 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meds", "0035_alter_appointment_created_at_bmi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 3, 3, 15, 37, 54, 866773)
            ),
        ),
    ]
