# Generated by Django 5.1.1 on 2025-04-06 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meds", "0049_alter_appointment_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 4, 7, 2, 5, 57, 736507)
            ),
        ),
        migrations.AlterField(
            model_name="doctorrequests",
            name="photo",
            field=models.ImageField(
                default="media/profile_photos/user.png", upload_to="profile_photos/"
            ),
        ),
        migrations.AlterField(
            model_name="doctors",
            name="photo",
            field=models.ImageField(
                default="media/profile_photos/user.png", upload_to="profile_photos/"
            ),
        ),
    ]
