# Generated by Django 5.1.1 on 2025-04-08 22:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meds", "0052_alter_appointment_created_at_prescription_medicine"),
    ]

    operations = [
        migrations.RenameField(
            model_name="medicine",
            old_name="quantity_per_dose",
            new_name="duration",
        ),
        migrations.RenameField(
            model_name="prescription",
            old_name="created_at",
            new_name="date",
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="duration_days",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="appointment",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="patient",
        ),
        migrations.AddField(
            model_name="medicine",
            name="quantity",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="prescription",
            name="diagnosis",
            field=models.TextField(default="fever"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="prescription",
            name="patient_age",
            field=models.IntegerField(default=27),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="prescription",
            name="patient_gender",
            field=models.CharField(default="male", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="prescription",
            name="patient_name",
            field=models.CharField(default="ayan", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="appointment",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 4, 9, 3, 33, 16, 212375)
            ),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="timing",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="meds.doctors"
            ),
        ),
    ]
